export const monstersMap1 = [
  {
    name: "agumon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/Agumon.webp",
      height: 25,
      width: 100,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Armadillomon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/Calumon_vg.webp",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Armadillomon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/Armadillomon.webp",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Aruraumon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/Aruraumon.webp",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Biyomon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/Biyomon.webp",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Calumon_vg",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/Calumon_vg.webp",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Gabumon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/gabumon.gif",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Gabumon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/gabumon.gif",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "patamon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/patamon.gif",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "Gaogamon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map2/Gaogamon_vg.webp",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  {
    name: "MetalGreymon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map2/MetalGreymon_vg.webp",
      height: 25,
      width: 25,
      base: 0,
      rotate: {
        pet: false,
        emeny: true,
      },
    },
  },
];
