import spriteSrc from "/chxk2csydkh81.png";
export const hero = {
  name: "Herói",
  reset: 0,
  rounds: 30,
  level: 1,
  experience: {
    current: 0,
    nextLevel: 200,
  },
  health: {
    current: 100,
    max: 100,
  },
  stamina: {
    current: 50,
    max: 50,
  },
  strength: 10,
  agility: 8,
  intelligence: 6,
  speed: 1,
  critical: 0,
  defense: 5,
  attackPower: 12,
  inventory: [],
  equipped: {
    weapon: null,
    armor: null,
    accessory: null,
  },
  position: {
    x: 0,
    y: 0,
  },
  direction: "down",
  statusEffects: [],
  gold: 0,
  skills: [],
  sprite: {
    img: spriteSrc,
    height: 25,
    width: 25,
    frameCount: 4,
    boxSize: 25,
    speed: 3,
  },
  pet: {
    name: "agumon",
    life: 100,
    nivel: 1,
    strength: 10,
    agility: 8,
    intelligence: 6,
    speed: 1,
    critical: 0,
    defense: 5,
    attackPower: 12,
    shadow: {
      height: 10,
      width: 25,
    },
    sprite: {
      img: "./diginom/map1/Agumon.webp",
      height: 25,
      width: 100,
      base: 0,
      rotate: {
        pet: true,
        emeny: false,
      },
    },
  },
  directionRowMap: {
    down: 0,
    left: 1,
    right: 2,
    up: 3,
  },
};
